// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.File.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "ImFile.pbobjc.h"
 #import "ImBaseDefine.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ImFileRoot

@implementation ImFileRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - ImFileRoot_FileDescriptor

static GPBFileDescriptor *ImFileRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"IM.File"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - IMFileLoginReq

@implementation IMFileLoginReq

@dynamic userId;
@dynamic taskId;
@dynamic fileRole;

typedef struct IMFileLoginReq__storage_ {
  uint32_t _has_storage_[1];
  uint32_t userId;
  ClientFileRole fileRole;
  NSString *taskId;
} IMFileLoginReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileLoginReq_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileLoginReq__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "taskId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileLoginReq_FieldNumber_TaskId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileLoginReq__storage_, taskId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fileRole",
        .dataTypeSpecific.enumDescFunc = ClientFileRole_EnumDescriptor,
        .number = IMFileLoginReq_FieldNumber_FileRole,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMFileLoginReq__storage_, fileRole),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileLoginReq class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileLoginReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t IMFileLoginReq_FileRole_RawValue(IMFileLoginReq *message) {
  GPBDescriptor *descriptor = [IMFileLoginReq descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileLoginReq_FieldNumber_FileRole];
  return GPBGetMessageInt32Field(message, field);
}

void SetIMFileLoginReq_FileRole_RawValue(IMFileLoginReq *message, int32_t value) {
  GPBDescriptor *descriptor = [IMFileLoginReq descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileLoginReq_FieldNumber_FileRole];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - IMFileLoginRsp

@implementation IMFileLoginRsp

@dynamic resultCode;
@dynamic taskId;

typedef struct IMFileLoginRsp__storage_ {
  uint32_t _has_storage_[1];
  uint32_t resultCode;
  NSString *taskId;
} IMFileLoginRsp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "resultCode",
        .dataTypeSpecific.className = NULL,
        .number = IMFileLoginRsp_FieldNumber_ResultCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileLoginRsp__storage_, resultCode),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "taskId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileLoginRsp_FieldNumber_TaskId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileLoginRsp__storage_, taskId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileLoginRsp class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileLoginRsp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - IMFileState

@implementation IMFileState

@dynamic state;
@dynamic taskId;
@dynamic userId;

typedef struct IMFileState__storage_ {
  uint32_t _has_storage_[1];
  ClientFileState state;
  uint32_t userId;
  NSString *taskId;
} IMFileState__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "state",
        .dataTypeSpecific.enumDescFunc = ClientFileState_EnumDescriptor,
        .number = IMFileState_FieldNumber_State,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileState__storage_, state),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "taskId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileState_FieldNumber_TaskId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileState__storage_, taskId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileState_FieldNumber_UserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMFileState__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileState class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileState__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t IMFileState_State_RawValue(IMFileState *message) {
  GPBDescriptor *descriptor = [IMFileState descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileState_FieldNumber_State];
  return GPBGetMessageInt32Field(message, field);
}

void SetIMFileState_State_RawValue(IMFileState *message, int32_t value) {
  GPBDescriptor *descriptor = [IMFileState descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileState_FieldNumber_State];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - IMFilePullDataReq

@implementation IMFilePullDataReq

@dynamic taskId;
@dynamic userId;
@dynamic transMode;
@dynamic offset;
@dynamic dataSize;

typedef struct IMFilePullDataReq__storage_ {
  uint32_t _has_storage_[1];
  uint32_t userId;
  TransferFileType transMode;
  uint32_t offset;
  uint32_t dataSize;
  NSString *taskId;
} IMFilePullDataReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "taskId",
        .dataTypeSpecific.className = NULL,
        .number = IMFilePullDataReq_FieldNumber_TaskId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFilePullDataReq__storage_, taskId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = IMFilePullDataReq_FieldNumber_UserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFilePullDataReq__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "transMode",
        .dataTypeSpecific.enumDescFunc = TransferFileType_EnumDescriptor,
        .number = IMFilePullDataReq_FieldNumber_TransMode,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMFilePullDataReq__storage_, transMode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "offset",
        .dataTypeSpecific.className = NULL,
        .number = IMFilePullDataReq_FieldNumber_Offset,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(IMFilePullDataReq__storage_, offset),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "dataSize",
        .dataTypeSpecific.className = NULL,
        .number = IMFilePullDataReq_FieldNumber_DataSize,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(IMFilePullDataReq__storage_, dataSize),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFilePullDataReq class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFilePullDataReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t IMFilePullDataReq_TransMode_RawValue(IMFilePullDataReq *message) {
  GPBDescriptor *descriptor = [IMFilePullDataReq descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFilePullDataReq_FieldNumber_TransMode];
  return GPBGetMessageInt32Field(message, field);
}

void SetIMFilePullDataReq_TransMode_RawValue(IMFilePullDataReq *message, int32_t value) {
  GPBDescriptor *descriptor = [IMFilePullDataReq descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFilePullDataReq_FieldNumber_TransMode];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - IMFilePullDataRsp

@implementation IMFilePullDataRsp

@dynamic resultCode;
@dynamic taskId;
@dynamic userId;
@dynamic offset;
@dynamic fileData;

typedef struct IMFilePullDataRsp__storage_ {
  uint32_t _has_storage_[1];
  uint32_t resultCode;
  uint32_t userId;
  uint32_t offset;
  NSString *taskId;
  NSData *fileData;
} IMFilePullDataRsp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "resultCode",
        .dataTypeSpecific.className = NULL,
        .number = IMFilePullDataRsp_FieldNumber_ResultCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFilePullDataRsp__storage_, resultCode),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "taskId",
        .dataTypeSpecific.className = NULL,
        .number = IMFilePullDataRsp_FieldNumber_TaskId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFilePullDataRsp__storage_, taskId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = IMFilePullDataRsp_FieldNumber_UserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMFilePullDataRsp__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "offset",
        .dataTypeSpecific.className = NULL,
        .number = IMFilePullDataRsp_FieldNumber_Offset,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(IMFilePullDataRsp__storage_, offset),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "fileData",
        .dataTypeSpecific.className = NULL,
        .number = IMFilePullDataRsp_FieldNumber_FileData,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(IMFilePullDataRsp__storage_, fileData),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFilePullDataRsp class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFilePullDataRsp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - IMFileReq

@implementation IMFileReq

@dynamic fromUserId;
@dynamic toUserId;
@dynamic fileName;
@dynamic fileSize;
@dynamic transMode;

typedef struct IMFileReq__storage_ {
  uint32_t _has_storage_[1];
  uint32_t fromUserId;
  uint32_t toUserId;
  uint32_t fileSize;
  TransferFileType transMode;
  NSString *fileName;
} IMFileReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fromUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileReq_FieldNumber_FromUserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileReq__storage_, fromUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "toUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileReq_FieldNumber_ToUserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileReq__storage_, toUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "fileName",
        .dataTypeSpecific.className = NULL,
        .number = IMFileReq_FieldNumber_FileName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMFileReq__storage_, fileName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fileSize",
        .dataTypeSpecific.className = NULL,
        .number = IMFileReq_FieldNumber_FileSize,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(IMFileReq__storage_, fileSize),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "transMode",
        .dataTypeSpecific.enumDescFunc = TransferFileType_EnumDescriptor,
        .number = IMFileReq_FieldNumber_TransMode,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(IMFileReq__storage_, transMode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileReq class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t IMFileReq_TransMode_RawValue(IMFileReq *message) {
  GPBDescriptor *descriptor = [IMFileReq descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileReq_FieldNumber_TransMode];
  return GPBGetMessageInt32Field(message, field);
}

void SetIMFileReq_TransMode_RawValue(IMFileReq *message, int32_t value) {
  GPBDescriptor *descriptor = [IMFileReq descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileReq_FieldNumber_TransMode];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - IMFileRsp

@implementation IMFileRsp

@dynamic resultCode;
@dynamic fromUserId;
@dynamic toUserId;
@dynamic fileName;
@dynamic taskId;
@dynamic ipAddrListArray, ipAddrListArray_Count;
@dynamic transMode;

typedef struct IMFileRsp__storage_ {
  uint32_t _has_storage_[1];
  uint32_t resultCode;
  uint32_t fromUserId;
  uint32_t toUserId;
  TransferFileType transMode;
  NSString *fileName;
  NSString *taskId;
  NSMutableArray *ipAddrListArray;
} IMFileRsp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "resultCode",
        .dataTypeSpecific.className = NULL,
        .number = IMFileRsp_FieldNumber_ResultCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileRsp__storage_, resultCode),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "fromUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileRsp_FieldNumber_FromUserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileRsp__storage_, fromUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "toUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileRsp_FieldNumber_ToUserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMFileRsp__storage_, toUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "fileName",
        .dataTypeSpecific.className = NULL,
        .number = IMFileRsp_FieldNumber_FileName,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(IMFileRsp__storage_, fileName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "taskId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileRsp_FieldNumber_TaskId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(IMFileRsp__storage_, taskId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "ipAddrListArray",
        .dataTypeSpecific.className = GPBStringifySymbol(IpAddr),
        .number = IMFileRsp_FieldNumber_IpAddrListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(IMFileRsp__storage_, ipAddrListArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "transMode",
        .dataTypeSpecific.enumDescFunc = TransferFileType_EnumDescriptor,
        .number = IMFileRsp_FieldNumber_TransMode,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(IMFileRsp__storage_, transMode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileRsp class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileRsp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t IMFileRsp_TransMode_RawValue(IMFileRsp *message) {
  GPBDescriptor *descriptor = [IMFileRsp descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileRsp_FieldNumber_TransMode];
  return GPBGetMessageInt32Field(message, field);
}

void SetIMFileRsp_TransMode_RawValue(IMFileRsp *message, int32_t value) {
  GPBDescriptor *descriptor = [IMFileRsp descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileRsp_FieldNumber_TransMode];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - IMFileNotify

@implementation IMFileNotify

@dynamic fromUserId;
@dynamic toUserId;
@dynamic fileName;
@dynamic fileSize;
@dynamic taskId;
@dynamic ipAddrListArray, ipAddrListArray_Count;
@dynamic transMode;
@dynamic offlineReady;

typedef struct IMFileNotify__storage_ {
  uint32_t _has_storage_[1];
  uint32_t fromUserId;
  uint32_t toUserId;
  uint32_t fileSize;
  TransferFileType transMode;
  uint32_t offlineReady;
  NSString *fileName;
  NSString *taskId;
  NSMutableArray *ipAddrListArray;
} IMFileNotify__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fromUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileNotify_FieldNumber_FromUserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileNotify__storage_, fromUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "toUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileNotify_FieldNumber_ToUserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileNotify__storage_, toUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "fileName",
        .dataTypeSpecific.className = NULL,
        .number = IMFileNotify_FieldNumber_FileName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMFileNotify__storage_, fileName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fileSize",
        .dataTypeSpecific.className = NULL,
        .number = IMFileNotify_FieldNumber_FileSize,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(IMFileNotify__storage_, fileSize),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "taskId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileNotify_FieldNumber_TaskId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(IMFileNotify__storage_, taskId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "ipAddrListArray",
        .dataTypeSpecific.className = GPBStringifySymbol(IpAddr),
        .number = IMFileNotify_FieldNumber_IpAddrListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(IMFileNotify__storage_, ipAddrListArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "transMode",
        .dataTypeSpecific.enumDescFunc = TransferFileType_EnumDescriptor,
        .number = IMFileNotify_FieldNumber_TransMode,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(IMFileNotify__storage_, transMode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "offlineReady",
        .dataTypeSpecific.className = NULL,
        .number = IMFileNotify_FieldNumber_OfflineReady,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(IMFileNotify__storage_, offlineReady),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileNotify class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileNotify__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t IMFileNotify_TransMode_RawValue(IMFileNotify *message) {
  GPBDescriptor *descriptor = [IMFileNotify descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileNotify_FieldNumber_TransMode];
  return GPBGetMessageInt32Field(message, field);
}

void SetIMFileNotify_TransMode_RawValue(IMFileNotify *message, int32_t value) {
  GPBDescriptor *descriptor = [IMFileNotify descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMFileNotify_FieldNumber_TransMode];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - IMFileHasOfflineReq

@implementation IMFileHasOfflineReq

@dynamic userId;
@dynamic attachData;

typedef struct IMFileHasOfflineReq__storage_ {
  uint32_t _has_storage_[1];
  uint32_t userId;
  NSData *attachData;
} IMFileHasOfflineReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileHasOfflineReq_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileHasOfflineReq__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "attachData",
        .dataTypeSpecific.className = NULL,
        .number = IMFileHasOfflineReq_FieldNumber_AttachData,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileHasOfflineReq__storage_, attachData),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileHasOfflineReq class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileHasOfflineReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - IMFileHasOfflineRsp

@implementation IMFileHasOfflineRsp

@dynamic userId;
@dynamic offlineFileListArray, offlineFileListArray_Count;
@dynamic ipAddrListArray, ipAddrListArray_Count;
@dynamic attachData;

typedef struct IMFileHasOfflineRsp__storage_ {
  uint32_t _has_storage_[1];
  uint32_t userId;
  NSMutableArray *offlineFileListArray;
  NSMutableArray *ipAddrListArray;
  NSData *attachData;
} IMFileHasOfflineRsp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileHasOfflineRsp_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileHasOfflineRsp__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "offlineFileListArray",
        .dataTypeSpecific.className = GPBStringifySymbol(OfflineFileInfo),
        .number = IMFileHasOfflineRsp_FieldNumber_OfflineFileListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(IMFileHasOfflineRsp__storage_, offlineFileListArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "ipAddrListArray",
        .dataTypeSpecific.className = GPBStringifySymbol(IpAddr),
        .number = IMFileHasOfflineRsp_FieldNumber_IpAddrListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(IMFileHasOfflineRsp__storage_, ipAddrListArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "attachData",
        .dataTypeSpecific.className = NULL,
        .number = IMFileHasOfflineRsp_FieldNumber_AttachData,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileHasOfflineRsp__storage_, attachData),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileHasOfflineRsp class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileHasOfflineRsp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - IMFileAddOfflineReq

@implementation IMFileAddOfflineReq

@dynamic fromUserId;
@dynamic toUserId;
@dynamic taskId;
@dynamic fileName;
@dynamic fileSize;

typedef struct IMFileAddOfflineReq__storage_ {
  uint32_t _has_storage_[1];
  uint32_t fromUserId;
  uint32_t toUserId;
  uint32_t fileSize;
  NSString *taskId;
  NSString *fileName;
} IMFileAddOfflineReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fromUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileAddOfflineReq_FieldNumber_FromUserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileAddOfflineReq__storage_, fromUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "toUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileAddOfflineReq_FieldNumber_ToUserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileAddOfflineReq__storage_, toUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "taskId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileAddOfflineReq_FieldNumber_TaskId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMFileAddOfflineReq__storage_, taskId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fileName",
        .dataTypeSpecific.className = NULL,
        .number = IMFileAddOfflineReq_FieldNumber_FileName,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(IMFileAddOfflineReq__storage_, fileName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fileSize",
        .dataTypeSpecific.className = NULL,
        .number = IMFileAddOfflineReq_FieldNumber_FileSize,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(IMFileAddOfflineReq__storage_, fileSize),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileAddOfflineReq class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileAddOfflineReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - IMFileDelOfflineReq

@implementation IMFileDelOfflineReq

@dynamic fromUserId;
@dynamic toUserId;
@dynamic taskId;

typedef struct IMFileDelOfflineReq__storage_ {
  uint32_t _has_storage_[1];
  uint32_t fromUserId;
  uint32_t toUserId;
  NSString *taskId;
} IMFileDelOfflineReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fromUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileDelOfflineReq_FieldNumber_FromUserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMFileDelOfflineReq__storage_, fromUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "toUserId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileDelOfflineReq_FieldNumber_ToUserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMFileDelOfflineReq__storage_, toUserId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "taskId",
        .dataTypeSpecific.className = NULL,
        .number = IMFileDelOfflineReq_FieldNumber_TaskId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMFileDelOfflineReq__storage_, taskId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMFileDelOfflineReq class]
                                     rootClass:[ImFileRoot class]
                                          file:ImFileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMFileDelOfflineReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
