// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Login.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserInfo;
GPB_ENUM_FWD_DECLARE(ClientType);
GPB_ENUM_FWD_DECLARE(KickReasonType);
GPB_ENUM_FWD_DECLARE(ResultType);
GPB_ENUM_FWD_DECLARE(UserStatType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImLoginRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ImLoginRoot : GPBRootObject
@end

#pragma mark - IMMsgServReq

/**
 * cmd id:		0x0101
 **/
@interface IMMsgServReq : GPBMessage

@end

#pragma mark - IMMsgServRsp

typedef GPB_ENUM(IMMsgServRsp_FieldNumber) {
  IMMsgServRsp_FieldNumber_ResultCode = 1,
  IMMsgServRsp_FieldNumber_PriorIp = 2,
  IMMsgServRsp_FieldNumber_BackipIp = 3,
  IMMsgServRsp_FieldNumber_Port = 4,
};

@interface IMMsgServRsp : GPBMessage

/** cmd id:		0x0102 */
@property(nonatomic, readwrite) enum ResultType resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *priorIp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *backipIp;

@property(nonatomic, readwrite) uint32_t port;

@end

/**
 * Fetches the raw value of a @c IMMsgServRsp's @c resultCode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t IMMsgServRsp_ResultCode_RawValue(IMMsgServRsp *message);
/**
 * Sets the raw value of an @c IMMsgServRsp's @c resultCode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetIMMsgServRsp_ResultCode_RawValue(IMMsgServRsp *message, int32_t value);

#pragma mark - IMLoginReq

typedef GPB_ENUM(IMLoginReq_FieldNumber) {
  IMLoginReq_FieldNumber_UserName = 1,
  IMLoginReq_FieldNumber_Password = 2,
  IMLoginReq_FieldNumber_OnlineStatus = 3,
  IMLoginReq_FieldNumber_ClientType = 4,
  IMLoginReq_FieldNumber_ClientVersion = 5,
};

@interface IMLoginReq : GPBMessage

/** cmd id:		0x0103 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@property(nonatomic, readwrite) enum UserStatType onlineStatus;

@property(nonatomic, readwrite) enum ClientType clientType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientVersion;

@end

/**
 * Fetches the raw value of a @c IMLoginReq's @c onlineStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t IMLoginReq_OnlineStatus_RawValue(IMLoginReq *message);
/**
 * Sets the raw value of an @c IMLoginReq's @c onlineStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetIMLoginReq_OnlineStatus_RawValue(IMLoginReq *message, int32_t value);

/**
 * Fetches the raw value of a @c IMLoginReq's @c clientType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t IMLoginReq_ClientType_RawValue(IMLoginReq *message);
/**
 * Sets the raw value of an @c IMLoginReq's @c clientType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetIMLoginReq_ClientType_RawValue(IMLoginReq *message, int32_t value);

#pragma mark - IMLoginRes

typedef GPB_ENUM(IMLoginRes_FieldNumber) {
  IMLoginRes_FieldNumber_ServerTime = 1,
  IMLoginRes_FieldNumber_ResultCode = 2,
  IMLoginRes_FieldNumber_ResultString = 3,
  IMLoginRes_FieldNumber_OnlineStatus = 4,
  IMLoginRes_FieldNumber_UserInfo = 5,
};

@interface IMLoginRes : GPBMessage

/** cmd id:		0x0104 */
@property(nonatomic, readwrite) uint32_t serverTime;

@property(nonatomic, readwrite) enum ResultType resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultString;

@property(nonatomic, readwrite) enum UserStatType onlineStatus;

@property(nonatomic, readwrite, strong, null_resettable) UserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@end

/**
 * Fetches the raw value of a @c IMLoginRes's @c resultCode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t IMLoginRes_ResultCode_RawValue(IMLoginRes *message);
/**
 * Sets the raw value of an @c IMLoginRes's @c resultCode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetIMLoginRes_ResultCode_RawValue(IMLoginRes *message, int32_t value);

/**
 * Fetches the raw value of a @c IMLoginRes's @c onlineStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t IMLoginRes_OnlineStatus_RawValue(IMLoginRes *message);
/**
 * Sets the raw value of an @c IMLoginRes's @c onlineStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetIMLoginRes_OnlineStatus_RawValue(IMLoginRes *message, int32_t value);

#pragma mark - IMLogoutReq

/**
 * cmd id:		0x0105
 **/
@interface IMLogoutReq : GPBMessage

@end

#pragma mark - IMLogoutRsp

typedef GPB_ENUM(IMLogoutRsp_FieldNumber) {
  IMLogoutRsp_FieldNumber_ResultCode = 1,
};

@interface IMLogoutRsp : GPBMessage

/** cmd id:		0x0106 */
@property(nonatomic, readwrite) uint32_t resultCode;

@end

#pragma mark - IMKickUser

typedef GPB_ENUM(IMKickUser_FieldNumber) {
  IMKickUser_FieldNumber_UserId = 1,
  IMKickUser_FieldNumber_KickReason = 2,
};

@interface IMKickUser : GPBMessage

/** cmd id:		0x0107 */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite) enum KickReasonType kickReason;

@end

/**
 * Fetches the raw value of a @c IMKickUser's @c kickReason property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t IMKickUser_KickReason_RawValue(IMKickUser *message);
/**
 * Sets the raw value of an @c IMKickUser's @c kickReason property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetIMKickUser_KickReason_RawValue(IMKickUser *message, int32_t value);

#pragma mark - IMDeviceTokenReq

typedef GPB_ENUM(IMDeviceTokenReq_FieldNumber) {
  IMDeviceTokenReq_FieldNumber_UserId = 1,
  IMDeviceTokenReq_FieldNumber_DeviceToken = 2,
  IMDeviceTokenReq_FieldNumber_ClientType = 3,
  IMDeviceTokenReq_FieldNumber_AttachData = 20,
};

@interface IMDeviceTokenReq : GPBMessage

/** cmd id:		0x0108 */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceToken;

@property(nonatomic, readwrite) enum ClientType clientType;

@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;

@end

/**
 * Fetches the raw value of a @c IMDeviceTokenReq's @c clientType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t IMDeviceTokenReq_ClientType_RawValue(IMDeviceTokenReq *message);
/**
 * Sets the raw value of an @c IMDeviceTokenReq's @c clientType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetIMDeviceTokenReq_ClientType_RawValue(IMDeviceTokenReq *message, int32_t value);

#pragma mark - IMDeviceTokenRsp

typedef GPB_ENUM(IMDeviceTokenRsp_FieldNumber) {
  IMDeviceTokenRsp_FieldNumber_UserId = 1,
  IMDeviceTokenRsp_FieldNumber_AttachData = 20,
};

@interface IMDeviceTokenRsp : GPBMessage

/** cmd id: 		0x0109 */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;

@end

#pragma mark - IMKickPCClientReq

typedef GPB_ENUM(IMKickPCClientReq_FieldNumber) {
  IMKickPCClientReq_FieldNumber_UserId = 1,
};

/**
 * 只给移动端请求
 **/
@interface IMKickPCClientReq : GPBMessage

/** cmd id:		0x010a */
@property(nonatomic, readwrite) uint32_t userId;

@end

#pragma mark - IMKickPCClientRsp

typedef GPB_ENUM(IMKickPCClientRsp_FieldNumber) {
  IMKickPCClientRsp_FieldNumber_UserId = 1,
  IMKickPCClientRsp_FieldNumber_ResultCode = 2,
};

@interface IMKickPCClientRsp : GPBMessage

/** cmd id: 		0x010b */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite) uint32_t resultCode;

@end

#pragma mark - IMPushShieldReq

typedef GPB_ENUM(IMPushShieldReq_FieldNumber) {
  IMPushShieldReq_FieldNumber_UserId = 1,
  IMPushShieldReq_FieldNumber_ShieldStatus = 2,
  IMPushShieldReq_FieldNumber_AttachData = 20,
};

/**
 * 一旦设置以后，22:00 -- 07:00不发送
 **/
@interface IMPushShieldReq : GPBMessage

/** cmd id:			0x010c */
@property(nonatomic, readwrite) uint32_t userId;

/** 1:开启，0：关闭 */
@property(nonatomic, readwrite) uint32_t shieldStatus;

/** 服务端用，客户端不用设置 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;

@end

#pragma mark - IMPushShieldRsp

typedef GPB_ENUM(IMPushShieldRsp_FieldNumber) {
  IMPushShieldRsp_FieldNumber_UserId = 1,
  IMPushShieldRsp_FieldNumber_ResultCode = 2,
  IMPushShieldRsp_FieldNumber_ShieldStatus = 3,
  IMPushShieldRsp_FieldNumber_AttachData = 20,
};

@interface IMPushShieldRsp : GPBMessage

/** cmd id:			0x010d */
@property(nonatomic, readwrite) uint32_t userId;

/** 值： 0:successed 1:failed */
@property(nonatomic, readwrite) uint32_t resultCode;

/** 值： 如果result_code值为0(successed)，则shield_status值设置， 1:开启， 0:关闭 */
@property(nonatomic, readwrite) uint32_t shieldStatus;

/** 服务端用，客户端不用设置 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;

@end

#pragma mark - IMQueryPushShieldReq

typedef GPB_ENUM(IMQueryPushShieldReq_FieldNumber) {
  IMQueryPushShieldReq_FieldNumber_UserId = 1,
  IMQueryPushShieldReq_FieldNumber_AttachData = 20,
};

/**
 * 如果用户重新安装app，第一次启动登录成功后，app主动查询
 * 服务端返回IMQueryPushShieldRsp
 **/
@interface IMQueryPushShieldReq : GPBMessage

/** cmd id:			0x010e */
@property(nonatomic, readwrite) uint32_t userId;

/** 服务端用，客户端不用设置 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;

@end

#pragma mark - IMQueryPushShieldRsp

typedef GPB_ENUM(IMQueryPushShieldRsp_FieldNumber) {
  IMQueryPushShieldRsp_FieldNumber_UserId = 1,
  IMQueryPushShieldRsp_FieldNumber_ResultCode = 2,
  IMQueryPushShieldRsp_FieldNumber_ShieldStatus = 3,
  IMQueryPushShieldRsp_FieldNumber_AttachData = 20,
};

@interface IMQueryPushShieldRsp : GPBMessage

/** cmd id:			0x010f */
@property(nonatomic, readwrite) uint32_t userId;

/** 值： 0:successed 1:failed */
@property(nonatomic, readwrite) uint32_t resultCode;

/** 值： 如果result_code值为0(successed)，则shield_status值设置， 1:开启， 0:关闭 */
@property(nonatomic, readwrite) uint32_t shieldStatus;

@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
