// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Server.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class IpAddr;
@class PushResult;
@class ServerUserStat;
@class ShieldStatus;
@class UserInfo;
@class UserTokenInfo;
GPB_ENUM_FWD_DECLARE(ClientType);
GPB_ENUM_FWD_DECLARE(TransferFileType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImServerRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ImServerRoot : GPBRootObject
@end

#pragma mark - IMStopReceivePacket

typedef GPB_ENUM(IMStopReceivePacket_FieldNumber) {
  IMStopReceivePacket_FieldNumber_Result = 1,
};

/**
 * db_proxy
 **/
@interface IMStopReceivePacket : GPBMessage

/** cmd id:   0x0702 */
@property(nonatomic, readwrite) uint32_t result;

@property(nonatomic, readwrite) BOOL hasResult;
@end

#pragma mark - IMValidateReq

typedef GPB_ENUM(IMValidateReq_FieldNumber) {
  IMValidateReq_FieldNumber_UserName = 1,
  IMValidateReq_FieldNumber_Password = 2,
  IMValidateReq_FieldNumber_AttachData = 20,
};

/**
 * db_proxy
 **/
@interface IMValidateReq : GPBMessage

/** cmd id:	0x0703 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;
/** Test to see if @c password has been set. */
@property(nonatomic, readwrite) BOOL hasPassword;

@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;
/** Test to see if @c attachData has been set. */
@property(nonatomic, readwrite) BOOL hasAttachData;

@end

#pragma mark - IMValidateRsp

typedef GPB_ENUM(IMValidateRsp_FieldNumber) {
  IMValidateRsp_FieldNumber_UserName = 1,
  IMValidateRsp_FieldNumber_ResultCode = 2,
  IMValidateRsp_FieldNumber_ResultString = 3,
  IMValidateRsp_FieldNumber_UserInfo = 4,
  IMValidateRsp_FieldNumber_AttachData = 20,
};

/**
 * db_proxy
 **/
@interface IMValidateRsp : GPBMessage

/** cmd id:	0x0704 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite) uint32_t resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *resultString;
/** Test to see if @c resultString has been set. */
@property(nonatomic, readwrite) BOOL hasResultString;

@property(nonatomic, readwrite, strong, null_resettable) UserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;
/** Test to see if @c attachData has been set. */
@property(nonatomic, readwrite) BOOL hasAttachData;

@end

#pragma mark - IMGetDeviceTokenReq

typedef GPB_ENUM(IMGetDeviceTokenReq_FieldNumber) {
  IMGetDeviceTokenReq_FieldNumber_UserIdArray = 1,
  IMGetDeviceTokenReq_FieldNumber_AttachData = 20,
};

/**
 * db_proxy
 **/
@interface IMGetDeviceTokenReq : GPBMessage

/** cmd id:	0x0705 */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *userIdArray;
/** The number of items in @c userIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userIdArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;
/** Test to see if @c attachData has been set. */
@property(nonatomic, readwrite) BOOL hasAttachData;

@end

#pragma mark - IMGetDeviceTokenRsp

typedef GPB_ENUM(IMGetDeviceTokenRsp_FieldNumber) {
  IMGetDeviceTokenRsp_FieldNumber_UserTokenInfoArray = 1,
  IMGetDeviceTokenRsp_FieldNumber_AttachData = 20,
};

/**
 * db_proxy
 **/
@interface IMGetDeviceTokenRsp : GPBMessage

/** cmd id:	0x0706 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserTokenInfo*> *userTokenInfoArray;
/** The number of items in @c userTokenInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userTokenInfoArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;
/** Test to see if @c attachData has been set. */
@property(nonatomic, readwrite) BOOL hasAttachData;

@end

#pragma mark - IMRoleSet

typedef GPB_ENUM(IMRoleSet_FieldNumber) {
  IMRoleSet_FieldNumber_Master = 1,
};

@interface IMRoleSet : GPBMessage

/** cmd id:	0x0707 */
@property(nonatomic, readwrite) uint32_t master;

@property(nonatomic, readwrite) BOOL hasMaster;
@end

#pragma mark - IMOnlineUserInfo

typedef GPB_ENUM(IMOnlineUserInfo_FieldNumber) {
  IMOnlineUserInfo_FieldNumber_UserStatListArray = 1,
};

@interface IMOnlineUserInfo : GPBMessage

/** cmd id:	0x0708 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ServerUserStat*> *userStatListArray;
/** The number of items in @c userStatListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userStatListArray_Count;

@end

#pragma mark - IMMsgServInfo

typedef GPB_ENUM(IMMsgServInfo_FieldNumber) {
  IMMsgServInfo_FieldNumber_Ip1 = 1,
  IMMsgServInfo_FieldNumber_Ip2 = 2,
  IMMsgServInfo_FieldNumber_Port = 3,
  IMMsgServInfo_FieldNumber_MaxConnCnt = 4,
  IMMsgServInfo_FieldNumber_CurConnCnt = 5,
  IMMsgServInfo_FieldNumber_HostName = 6,
};

@interface IMMsgServInfo : GPBMessage

/** cmd id:	0x0709 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ip1;
/** Test to see if @c ip1 has been set. */
@property(nonatomic, readwrite) BOOL hasIp1;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ip2;
/** Test to see if @c ip2 has been set. */
@property(nonatomic, readwrite) BOOL hasIp2;

@property(nonatomic, readwrite) uint32_t port;

@property(nonatomic, readwrite) BOOL hasPort;
@property(nonatomic, readwrite) uint32_t maxConnCnt;

@property(nonatomic, readwrite) BOOL hasMaxConnCnt;
@property(nonatomic, readwrite) uint32_t curConnCnt;

@property(nonatomic, readwrite) BOOL hasCurConnCnt;
@property(nonatomic, readwrite, copy, null_resettable) NSString *hostName;
/** Test to see if @c hostName has been set. */
@property(nonatomic, readwrite) BOOL hasHostName;

@end

#pragma mark - IMUserStatusUpdate

typedef GPB_ENUM(IMUserStatusUpdate_FieldNumber) {
  IMUserStatusUpdate_FieldNumber_UserStatus = 1,
  IMUserStatusUpdate_FieldNumber_UserId = 2,
  IMUserStatusUpdate_FieldNumber_ClientType = 3,
};

@interface IMUserStatusUpdate : GPBMessage

/** cmd id:	0x070a */
@property(nonatomic, readwrite) uint32_t userStatus;

@property(nonatomic, readwrite) BOOL hasUserStatus;
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite) enum ClientType clientType;

@property(nonatomic, readwrite) BOOL hasClientType;
@end

#pragma mark - IMUserCntUpdate

typedef GPB_ENUM(IMUserCntUpdate_FieldNumber) {
  IMUserCntUpdate_FieldNumber_UserAction = 1,
  IMUserCntUpdate_FieldNumber_UserId = 2,
};

@interface IMUserCntUpdate : GPBMessage

/** cmd id:	0x070b */
@property(nonatomic, readwrite) uint32_t userAction;

@property(nonatomic, readwrite) BOOL hasUserAction;
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@end

#pragma mark - IMServerKickUser

typedef GPB_ENUM(IMServerKickUser_FieldNumber) {
  IMServerKickUser_FieldNumber_UserId = 1,
  IMServerKickUser_FieldNumber_ClientType = 2,
  IMServerKickUser_FieldNumber_Reason = 3,
};

@interface IMServerKickUser : GPBMessage

/** cmd id:	0x070d */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite) enum ClientType clientType;

@property(nonatomic, readwrite) BOOL hasClientType;
/** KICK_REASON_DUPLICATE_USER = 1; */
@property(nonatomic, readwrite) uint32_t reason;

@property(nonatomic, readwrite) BOOL hasReason;
@end

#pragma mark - IMServerPCLoginStatusNotify

typedef GPB_ENUM(IMServerPCLoginStatusNotify_FieldNumber) {
  IMServerPCLoginStatusNotify_FieldNumber_UserId = 1,
  IMServerPCLoginStatusNotify_FieldNumber_LoginStatus = 2,
};

@interface IMServerPCLoginStatusNotify : GPBMessage

/** cmd id:	0x070e */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
/** 1: on   0: off */
@property(nonatomic, readwrite) uint32_t loginStatus;

@property(nonatomic, readwrite) BOOL hasLoginStatus;
@end

#pragma mark - IMPushToUserReq

typedef GPB_ENUM(IMPushToUserReq_FieldNumber) {
  IMPushToUserReq_FieldNumber_Flash = 1,
  IMPushToUserReq_FieldNumber_Data_p = 2,
  IMPushToUserReq_FieldNumber_UserTokenListArray = 3,
};

@interface IMPushToUserReq : GPBMessage

/** cmd id:	0x070f */
@property(nonatomic, readwrite, copy, null_resettable) NSString *flash;
/** Test to see if @c flash has been set. */
@property(nonatomic, readwrite) BOOL hasFlash;

@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserTokenInfo*> *userTokenListArray;
/** The number of items in @c userTokenListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userTokenListArray_Count;

@end

#pragma mark - IMPushToUserRsp

typedef GPB_ENUM(IMPushToUserRsp_FieldNumber) {
  IMPushToUserRsp_FieldNumber_PushResultListArray = 1,
};

@interface IMPushToUserRsp : GPBMessage

/** cmd id:	0x0710 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PushResult*> *pushResultListArray;
/** The number of items in @c pushResultListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pushResultListArray_Count;

@end

#pragma mark - IMGroupGetShieldReq

typedef GPB_ENUM(IMGroupGetShieldReq_FieldNumber) {
  IMGroupGetShieldReq_FieldNumber_GroupId = 1,
  IMGroupGetShieldReq_FieldNumber_UserIdArray = 2,
  IMGroupGetShieldReq_FieldNumber_AttachData = 20,
};

@interface IMGroupGetShieldReq : GPBMessage

/** cmd id:			0x0711 */
@property(nonatomic, readwrite) uint32_t groupId;

@property(nonatomic, readwrite) BOOL hasGroupId;
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *userIdArray;
/** The number of items in @c userIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userIdArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;
/** Test to see if @c attachData has been set. */
@property(nonatomic, readwrite) BOOL hasAttachData;

@end

#pragma mark - IMGroupGetShieldRsp

typedef GPB_ENUM(IMGroupGetShieldRsp_FieldNumber) {
  IMGroupGetShieldRsp_FieldNumber_GroupId = 1,
  IMGroupGetShieldRsp_FieldNumber_ShieldStatusListArray = 2,
  IMGroupGetShieldRsp_FieldNumber_AttachData = 20,
};

@interface IMGroupGetShieldRsp : GPBMessage

/** cmd id: 			0x0712 */
@property(nonatomic, readwrite) uint32_t groupId;

@property(nonatomic, readwrite) BOOL hasGroupId;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ShieldStatus*> *shieldStatusListArray;
/** The number of items in @c shieldStatusListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger shieldStatusListArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;
/** Test to see if @c attachData has been set. */
@property(nonatomic, readwrite) BOOL hasAttachData;

@end

#pragma mark - IMFileTransferReq

typedef GPB_ENUM(IMFileTransferReq_FieldNumber) {
  IMFileTransferReq_FieldNumber_FromUserId = 1,
  IMFileTransferReq_FieldNumber_ToUserId = 2,
  IMFileTransferReq_FieldNumber_FileName = 3,
  IMFileTransferReq_FieldNumber_FileSize = 4,
  IMFileTransferReq_FieldNumber_TransMode = 5,
  IMFileTransferReq_FieldNumber_AttachData = 20,
};

@interface IMFileTransferReq : GPBMessage

/** cmd id:			0x0715 */
@property(nonatomic, readwrite) uint32_t fromUserId;

@property(nonatomic, readwrite) BOOL hasFromUserId;
@property(nonatomic, readwrite) uint32_t toUserId;

@property(nonatomic, readwrite) BOOL hasToUserId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;
/** Test to see if @c fileName has been set. */
@property(nonatomic, readwrite) BOOL hasFileName;

@property(nonatomic, readwrite) uint32_t fileSize;

@property(nonatomic, readwrite) BOOL hasFileSize;
@property(nonatomic, readwrite) enum TransferFileType transMode;

@property(nonatomic, readwrite) BOOL hasTransMode;
@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;
/** Test to see if @c attachData has been set. */
@property(nonatomic, readwrite) BOOL hasAttachData;

@end

#pragma mark - IMFileTransferRsp

typedef GPB_ENUM(IMFileTransferRsp_FieldNumber) {
  IMFileTransferRsp_FieldNumber_ResultCode = 1,
  IMFileTransferRsp_FieldNumber_FromUserId = 2,
  IMFileTransferRsp_FieldNumber_ToUserId = 3,
  IMFileTransferRsp_FieldNumber_FileName = 4,
  IMFileTransferRsp_FieldNumber_FileSize = 5,
  IMFileTransferRsp_FieldNumber_TaskId = 6,
  IMFileTransferRsp_FieldNumber_TransMode = 7,
  IMFileTransferRsp_FieldNumber_AttachData = 20,
};

@interface IMFileTransferRsp : GPBMessage

/** cmd id:			0x0716 */
@property(nonatomic, readwrite) uint32_t resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite) uint32_t fromUserId;

@property(nonatomic, readwrite) BOOL hasFromUserId;
@property(nonatomic, readwrite) uint32_t toUserId;

@property(nonatomic, readwrite) BOOL hasToUserId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;
/** Test to see if @c fileName has been set. */
@property(nonatomic, readwrite) BOOL hasFileName;

@property(nonatomic, readwrite) uint32_t fileSize;

@property(nonatomic, readwrite) BOOL hasFileSize;
@property(nonatomic, readwrite, copy, null_resettable) NSString *taskId;
/** Test to see if @c taskId has been set. */
@property(nonatomic, readwrite) BOOL hasTaskId;

@property(nonatomic, readwrite) enum TransferFileType transMode;

@property(nonatomic, readwrite) BOOL hasTransMode;
@property(nonatomic, readwrite, copy, null_resettable) NSData *attachData;
/** Test to see if @c attachData has been set. */
@property(nonatomic, readwrite) BOOL hasAttachData;

@end

#pragma mark - IMFileServerIPReq

/**
 * cmd id:			0x0717
 **/
@interface IMFileServerIPReq : GPBMessage

@end

#pragma mark - IMFileServerIPRsp

typedef GPB_ENUM(IMFileServerIPRsp_FieldNumber) {
  IMFileServerIPRsp_FieldNumber_IpAddrListArray = 1,
};

@interface IMFileServerIPRsp : GPBMessage

/** cmd id:			0x0718 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<IpAddr*> *ipAddrListArray;
/** The number of items in @c ipAddrListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ipAddrListArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
