// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.SwitchService.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImSwitchServiceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ImSwitchServiceRoot : GPBRootObject
@end

#pragma mark - IMP2PCmdMsg

typedef GPB_ENUM(IMP2PCmdMsg_FieldNumber) {
  IMP2PCmdMsg_FieldNumber_FromUserId = 1,
  IMP2PCmdMsg_FieldNumber_ToUserId = 2,
  IMP2PCmdMsg_FieldNumber_CmdMsgData = 3,
};

@interface IMP2PCmdMsg : GPBMessage

/** cmd id:		0x0601 */
@property(nonatomic, readwrite) uint32_t fromUserId;

@property(nonatomic, readwrite) BOOL hasFromUserId;
@property(nonatomic, readwrite) uint32_t toUserId;

@property(nonatomic, readwrite) BOOL hasToUserId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *cmdMsgData;
/** Test to see if @c cmdMsgData has been set. */
@property(nonatomic, readwrite) BOOL hasCmdMsgData;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
