// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.SwitchService.proto

#ifndef PROTOBUF_IM_2eSwitchService_2eproto__INCLUDED
#define PROTOBUF_IM_2eSwitchService_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_IM_2eSwitchService_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsIMP2PCmdMsgImpl();
void InitDefaultsIMP2PCmdMsg();
inline void InitDefaults() {
  InitDefaultsIMP2PCmdMsg();
}
}  // namespace protobuf_IM_2eSwitchService_2eproto
namespace IM {
namespace SwitchService {
class IMP2PCmdMsg;
class IMP2PCmdMsgDefaultTypeInternal;
extern IMP2PCmdMsgDefaultTypeInternal _IMP2PCmdMsg_default_instance_;
}  // namespace SwitchService
}  // namespace IM
namespace IM {
namespace SwitchService {

// ===================================================================

class IMP2PCmdMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:IM.SwitchService.IMP2PCmdMsg) */ {
 public:
  IMP2PCmdMsg();
  virtual ~IMP2PCmdMsg();

  IMP2PCmdMsg(const IMP2PCmdMsg& from);

  inline IMP2PCmdMsg& operator=(const IMP2PCmdMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IMP2PCmdMsg(IMP2PCmdMsg&& from) noexcept
    : IMP2PCmdMsg() {
    *this = ::std::move(from);
  }

  inline IMP2PCmdMsg& operator=(IMP2PCmdMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const IMP2PCmdMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IMP2PCmdMsg* internal_default_instance() {
    return reinterpret_cast<const IMP2PCmdMsg*>(
               &_IMP2PCmdMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(IMP2PCmdMsg* other);
  friend void swap(IMP2PCmdMsg& a, IMP2PCmdMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IMP2PCmdMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  IMP2PCmdMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const IMP2PCmdMsg& from);
  void MergeFrom(const IMP2PCmdMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(IMP2PCmdMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string cmd_msg_data = 3;
  void clear_cmd_msg_data();
  static const int kCmdMsgDataFieldNumber = 3;
  const ::std::string& cmd_msg_data() const;
  void set_cmd_msg_data(const ::std::string& value);
  #if LANG_CXX11
  void set_cmd_msg_data(::std::string&& value);
  #endif
  void set_cmd_msg_data(const char* value);
  void set_cmd_msg_data(const char* value, size_t size);
  ::std::string* mutable_cmd_msg_data();
  ::std::string* release_cmd_msg_data();
  void set_allocated_cmd_msg_data(::std::string* cmd_msg_data);

  // uint32 from_user_id = 1;
  void clear_from_user_id();
  static const int kFromUserIdFieldNumber = 1;
  ::google::protobuf::uint32 from_user_id() const;
  void set_from_user_id(::google::protobuf::uint32 value);

  // uint32 to_user_id = 2;
  void clear_to_user_id();
  static const int kToUserIdFieldNumber = 2;
  ::google::protobuf::uint32 to_user_id() const;
  void set_to_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:IM.SwitchService.IMP2PCmdMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr cmd_msg_data_;
  ::google::protobuf::uint32 from_user_id_;
  ::google::protobuf::uint32 to_user_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_IM_2eSwitchService_2eproto::TableStruct;
  friend void ::protobuf_IM_2eSwitchService_2eproto::InitDefaultsIMP2PCmdMsgImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IMP2PCmdMsg

// uint32 from_user_id = 1;
inline void IMP2PCmdMsg::clear_from_user_id() {
  from_user_id_ = 0u;
}
inline ::google::protobuf::uint32 IMP2PCmdMsg::from_user_id() const {
  // @@protoc_insertion_point(field_get:IM.SwitchService.IMP2PCmdMsg.from_user_id)
  return from_user_id_;
}
inline void IMP2PCmdMsg::set_from_user_id(::google::protobuf::uint32 value) {
  
  from_user_id_ = value;
  // @@protoc_insertion_point(field_set:IM.SwitchService.IMP2PCmdMsg.from_user_id)
}

// uint32 to_user_id = 2;
inline void IMP2PCmdMsg::clear_to_user_id() {
  to_user_id_ = 0u;
}
inline ::google::protobuf::uint32 IMP2PCmdMsg::to_user_id() const {
  // @@protoc_insertion_point(field_get:IM.SwitchService.IMP2PCmdMsg.to_user_id)
  return to_user_id_;
}
inline void IMP2PCmdMsg::set_to_user_id(::google::protobuf::uint32 value) {
  
  to_user_id_ = value;
  // @@protoc_insertion_point(field_set:IM.SwitchService.IMP2PCmdMsg.to_user_id)
}

// string cmd_msg_data = 3;
inline void IMP2PCmdMsg::clear_cmd_msg_data() {
  cmd_msg_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& IMP2PCmdMsg::cmd_msg_data() const {
  // @@protoc_insertion_point(field_get:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
  return cmd_msg_data_.GetNoArena();
}
inline void IMP2PCmdMsg::set_cmd_msg_data(const ::std::string& value) {
  
  cmd_msg_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}
#if LANG_CXX11
inline void IMP2PCmdMsg::set_cmd_msg_data(::std::string&& value) {
  
  cmd_msg_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}
#endif
inline void IMP2PCmdMsg::set_cmd_msg_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  cmd_msg_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}
inline void IMP2PCmdMsg::set_cmd_msg_data(const char* value, size_t size) {
  
  cmd_msg_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}
inline ::std::string* IMP2PCmdMsg::mutable_cmd_msg_data() {
  
  // @@protoc_insertion_point(field_mutable:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
  return cmd_msg_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* IMP2PCmdMsg::release_cmd_msg_data() {
  // @@protoc_insertion_point(field_release:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
  
  return cmd_msg_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IMP2PCmdMsg::set_allocated_cmd_msg_data(::std::string* cmd_msg_data) {
  if (cmd_msg_data != NULL) {
    
  } else {
    
  }
  cmd_msg_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cmd_msg_data);
  // @@protoc_insertion_point(field_set_allocated:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace SwitchService
}  // namespace IM

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_IM_2eSwitchService_2eproto__INCLUDED
